@echo off
echo Content-Type: text/plain
rem
echo PATH_INFO=%PATH_INFO% 
echo PATH_TRANSLATED=%PATH_TRANSLATED% 
echo QUERY_STRING=%QUERY_STRING%
echo SERVER_NAME=%SERVER_NAME% 
echo SCRIPT_NAME=%SCRIPT_NAME%
